version: "3.8"

# --------------------
#   gluetun
# --------------------
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8080:8080"  # qBittorrent WebUI
      - "6881:6881"  # qBittorrent port
      - "6881:6881/udp"
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - TZ=${TZ}
    volumes:
      - C:\media\config\gluetun:/gluetun
    restart: unless-stopped
# --------------------
#   qbittorrent
# --------------------
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - C:\media\config\qbittorrent:/config
      - C:\media\downloads:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped

# --------------------
#   watchtower
# --------------------
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

# --------------------
#     radarr
# --------------------
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - C:\media\config\radarr:/config
      - C:\media\movies:/movies
      - C:\media\downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped

# --------------------
#   Prowlarr
# --------------------
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - C:\media\config\prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    ports:
      - "8191:8191"
    restart: unless-stopped

# --------------------
#     Sonarr
# --------------------
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}  # references the values in the .env file
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - C:\media\config\sonarr:/config
      - C:\media\tv:/tv
      - C:\media\downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped

# --------------------
#     Plex
# --------------------
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - C:\media\config\plex:/config
      - C:\media\movies:/movies
      - C:\media\tv:/tv
    ports:
      - "32400:32400"
    restart: unless-stopped

# --------------------
#   Overseerr
# --------------------
  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - C:\media\config\overseerr:/config
    ports:
      - "5055:5055"
    restart: unless-stopped

# --------------------
#   Homarr
# --------------------
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    volumes:
      - C:\media\config\homarr:/appdata
    ports:
      - "7575:7575"
    environment:
      - TZ=${TZ}
      - SECRET_ENCRYPTION_KEY=af6eadbe6729ee364ae16f4a99a0ce7e47ef12b9c4bda6db4001753d6f32d480
    restart: unless-stopped

# --------------------
#   dash. -- system metrics
# --------------------
  dashdot:
    image: mauricenino/dashdot:latest
    container_name: dashdot
    restart: unless-stopped
    privileged: true
    ports:
      - "3002:3001"
    volumes:
      - /:/mnt/host:ro

# --------------------
#   LazyLibrarian
# --------------------
  lazylibrarian:
    image: linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - C:\media\config\lazylibrarian:/config
      - C:\media\books:/books
      - C:\media\downloads:/downloads
    ports:
      - "5299:5299"
    restart: unless-stopped
    
# --------------------
#   AudioShelf
# --------------------
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - C:\media\books\audiobooks:/audiobooks
      - C:\media\config\audiobookshelf:/config
      - C:\media\books\metadata:/metadata
    ports:
      - "13378:80"
    restart: unless-stopped
