version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "8082:80"      # Web interface
      - "8443:443"     # HTTPS
      - "5335:53/tcp"  # DNS
      - "5335:53/udp"  # DNS
    environment:
      - TZ=America/Chicago
    volumes:
      - ./etc-pihole:/etc/pihole
    cap_add:
      - CAP_NET_ADMIN
    restart: unless-stopped
