services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
     - "8082:80"
     - "8443:443"
     - "53:53/tcp"    # Change from 5335
     - "53:53/udp"    # Change from 5335
    environment:
      - TZ=America/Chicago
    volumes:
      - ./etc-pihole:/etc/pihole
    cap_add:
      - CAP_NET_ADMIN
    restart: unless-stopped
