# docker-compose.yml
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "5335:53/tcp"    # Different port to avoid conflicts
      - "5335:53/udp"
      - "8080:80/tcp"    # Web interface
      - "8443:443/tcp"
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      # Optional: Set custom DNS servers (Cloudflare by default)
      # PIHOLE_DNS_: "1.1.1.1;1.0.0.1"
    volumes:
      - './etc-pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped